
stages:
  - build
  - test

build website:
    image: node:12
    stage: build
    script:
      - unset CI #   get rid of "Treating warnings as errors because process.env.CI = true" error
      - npm install
      - npm install -g create-react-app
      - npm run build
    artifacts:
        paths: 
          - ./build

test artifact:
    image: alpine
    stage: test
    script:
      - grep -q "React" ./build/index.html

test website:
    image: node:12
    stage: test
    script:
      - npm install
      - npm install -g create-react-app 
      - npm start &
      - sleep 5 #not the smartest way to do it because it will always wait 5 seconds, despite how fast server is
      - curl "http://localhost:3000" | tac | tac | grep -q "React"
      
    
