image: node:12

stage:
  - build
  - test

build website:
    stage: build
    script:
      - unset CI #   get rid of "Treating warnings as errors because process.env.CI = true" error
      - npm install
      - npm install -g create-react-app
      - npm run build
    artifacts:
        paths: 
          - ./build

test artifact:
    stage: test
    script:
      - grep "React" ./build/index.html
      - grep "xxxxD" ./build/index.html
    
