version: '3'

services: 
  backend:
    build: 
      context: ./djangonba # folder backend
    volumes:
      - ./djangonba:/app/backend
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: 
      context: .
    command: >
      sh -c "npm start"
    volumes: 
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true

