version: '2'
services:
  base:
    image: node:12
    volumes:
      - .:/code
    working_dir: /code
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
  create-bundles:
    extends:
      service: base
    command: npm run create-bundles
    