version: '3'

services: 
  djangonba:
    env_file: .env
    build: 
      context: ./djangonba # folder
    volumes:
      - ./djangonba:/djangonba
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&      
             python manage.py runserver 0.0.0.0:8000"
    environment:
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    depends_on:
        - db
    
  db:
    env_file: .env
    image: postgres:12-alpine
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  frontend:
    env_file: .env
    build: 
      context: .
    command: >
      sh -c "npm start"
    volumes: 
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true

