version: '3'

services: 
  backend:
    build: ./djangonba # folder backend
    command:  python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangonba:/app/backend
    ports:
      - "8000:8000"
  frontend:
    build: .
    command: npm start
    volumes: 
      - .:/app
    environment: 
      - NODE_ENV=development
    ports:
      - "3000:3000"
    stdin_open: true

