export {default as Home} from './layout/Home'
export {default as Header} from './layout/Header'
export {default as Games} from './Games'
export {default as Login} from './auth/LogIn'
export {default as Register} from './auth/Register'