# Generated by Django 3.0.6 on 2020-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='token',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
