# Generated by Django 3.0.7 on 2020-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(max_length=120, verbose_name='Game-Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameid',
            field=models.CharField(max_length=120, verbose_name='Game-Id'),
        ),
    ]
